### ISSUE TITLE
Issue importing sheet

### ISSUE THREAD

**Issue by kmanrulze** [zarmstrong/hlo-importer#1]
Importing sheets by tokens seems to be broken. Verified proper tokens were being used for imports, and verified with a secondary source that the importing function is broken on other machines as well with several different types of sheets. 

Only outside variable is that in Hero Labs, characters are using custom ancestry options. Wasn't an issue before, so may be due to a breaking change on the PF2e sheet set, but below is the error that occurs on importing

![image](https://user-images.githubusercontent.com/24468783/104948385-33d73480-598b-11eb-910c-d94af7b78eb8.png)

**Comment by zarmstrong** [comment]
Thanks, I have a work-around in place, no update needed to the module. Something went funky with their SSL cert, so I'm going to have to do further digging to put in a proper fix.

**Comment by zarmstrong** [comment]
![image](https://user-images.githubusercontent.com/565269/104997836-81818a80-59e7-11eb-90cc-14c2ff23d32b.png)

**Comment by zarmstrong** [comment]
They have misconfigured their server. Not an issue on my end.  That said, I should put in some better error handling to prevent this from silently failing.

**Comment by kmanrulze** [comment]
Fair enough. Yeah having a front end message of some kind would be good to have, or even some console message at least to narrow down issues when they happen
