### ISSUE TITLE
HLO: Focus Spell Import

### ISSUE THREAD

**Issue by JamzTheMan** [zarmstrong/hlo-importer#14]
I think the PF2E crew changed Focus Points under the hood...

Import created broken Focus spell entry with no focus points. (so deleted and created a new one)

**Comment by zarmstrong** [comment]
Will investigate this weekend. What version of PF2e system did you notice this in?

**Comment by JamzTheMan** [comment]
PFS Wizard: `$DDwTd5r~@P2#`

This is a fresh world, only this mod active, latest PF2E, just did a new import...
![image](https://user-images.githubusercontent.com/8051654/128899105-1a429ed2-3967-4639-96d6-77ab98e5574a.png)

**Comment by zarmstrong** [comment]
I can reproduce. Investigating the changes.

**Comment by zarmstrong** [comment]
if you're not the GM, have the GM update the module and try again

**Comment by JamzTheMan** [comment]
Yep, cool, Focus spells/points are creating as expected! I consider this one closed. :)
