### ISSUE TITLE
HLO Import of Character with Crafting 

### ISSUE THREAD

**Issue by KevinRichard-GM** [zarmstrong/hlo-importer#15]
I posted this under the [hlo-to-fvtt-pf2-public](https://github.com/zarmstrong/hlo-to-fvtt-pf2-public) but I haven't seen traffic there since May so I cross posted it here.

[https://github.com/zarmstrong/hlo-to-fvtt-pf2-public/issues/13#issue-1160071664](url)

**Comment by KevinRichard-GM** [comment]
Appears the latest PF2 ruleset update for FoundryVTT fixed the issue.

**Comment by zarmstrong** [comment]
Thanks for the update @KevinRichard-GM. Glad this resolved it for you.
