### ISSUE TITLE
Module appears on Starfinder worlds

### ISSUE THREAD

**Issue by avagdumortesin** [zarmstrong/hlo-importer#16]
![image](https://user-images.githubusercontent.com/55938242/160258829-48ae4d36-733a-4df5-baf2-a4965b90bc64.png)

As seen in the image, the HeroLab Online PF2e Import Tool module appears on worlds with the Starfinder system installed. None of the documentation shows that HLO Starfinder characters are supported (which I would absolutely love to have), so I'm assuming this is simply not restricted to PF2 worlds.

If this is a feature you are looking at adding, I would love to assist.

**Comment by zarmstrong** [comment]
Thanks for the heads up!  Just a small display bug. I have no plans to support Starfinder at this time.
Pushed a fix for this
