### ISSUE TITLE
V11 compatibility

### ISSUE THREAD

**Issue by iotech-fvtt** [zarmstrong/hlo-importer#21]
PF2 is not V11 compatible, Please consider re-working HLO Importer for V11 compatibility

**Comment by subourbonite** [comment]
I'd love an update on this, too, as I use this all the time.

**Comment by zarmstrong** [comment]
The PF2e foundry dev team has made the characters so complex and automated that maintaining this further doesn't make any sense. The drag-and-drop character building does a lot of automation that would be massive efforts of work to basically duplicate what they do automatically.
