### ISSUE TITLE
HLO: Request for better ABC support

### ISSUE THREAD

**Issue by JamzTheMan** [zarmstrong/hlo-importer#5]
Now that the Ancestry, Backgrounds, and Classes are drag n drop, and the classes now have "feat slots", could the HLO import use the compendium based ABC's vs generating them manually (the old way)?

**Comment by zarmstrong** [comment]
I need to get a better understanding of how they work before I can work on it, and life has been super busy that I haven't had the time to do a deep dive yet. It's on the to do list, though!

**Comment by zarmstrong** [comment]
The vast majority of things should now work. The only thing I can't really figure out from the HLO export is when a feat was picked and what category it falls under

**Comment by JamzTheMan** [comment]
Imported my Wizard this weekend, things seem to work much better!

And ya, that's even a pain using the Interface. It's horrible at clearly (or even at all) telling you that you took x feat at x level.

I *love* how Pathbuilder did it better and even lets you pre-plan your hero. Been asking Hero labs to do that *forever*...

**Comment by zarmstrong** [comment]
Yeah, I think we might be waiting a long time for them to add that!  Gonna close this out for now.
