### ISSUE TITLE
Unable to import character

### ISSUE THREAD

**Issue by StevenVanDyk** [zarmstrong/hlo-importer#7]
Started a while ago I have a Cleric level 7 in hlo
I generate the code and use the token  to try to import.
it comes back with the log to confirm.

the Character imported into cannot open.
 I tried with all other modules turned off incase of an incompatibility
and in a new world

**Comment by zarmstrong** [comment]
Can you provide the token please?  I'll need that to dig in.

**Comment by StevenVanDyk** [comment]
$pDaWYEQ~@P2#

Abs thanks

**Comment by zarmstrong** [comment]
Yep, just noticed it on the other project :) Thanks

**Comment by zarmstrong** [comment]
It seems to be the ~ character. Can you hit the button in Hero Lab that says Revoke Element Token, then get a new element token?

**Comment by zarmstrong** [comment]
Actually, ignore that. That doesn't seem to help.  I'll keep digging

**Comment by StevenVanDyk** [comment]
$QD8VR8o~@P2#

I tried a few here is the latest
They all came up with the ~

**Comment by zarmstrong** [comment]
Yeah, I noticed that too. I'm digging in deeper, thanks for the updated token.

**Comment by zarmstrong** [comment]
I'm honestly thinking there's an issue with their API. I am opening a ticket with them.

**Comment by StevenVanDyk** [comment]
ok thanks. Much appreciate the Help and the Module

**Comment by zarmstrong** [comment]
No problem. They are somewhat slow to reply, so I'll update when I hear back. Going to try some back channels to see if I can get a faster response

**Comment by zarmstrong** [comment]
Ok, it's working now. Can you check the element token again?  The issue seems to be the lowercase P in the @p2#

**Comment by StevenVanDyk** [comment]
$QD8VR8o~@P2#

**Comment by zarmstrong** [comment]
if you revoke and request a new one, does it have a capital `@P2#` at the end or lowercase `@p2#`

**Comment by zarmstrong** [comment]
Oh it looks like github is making it lowercase. Damnit github!  gotta put the token inside of ` marks to prevent it from lowercasing it

**Comment by StevenVanDyk** [comment]
Yeah they all seem to

$sDBy520~@P2#
Is the latest

I tried revoking and creating a couple times

**Comment by zarmstrong** [comment]
Now that that's out of the way, let me dig in some more with that token lol

**Comment by StevenVanDyk** [comment]
$sDBy520~@P2#
***@***.***D73C3B.F9FD67F0]
As an image as well so it cant “help us” with the text

**Comment by zarmstrong** [comment]
I was able to import the PC with the token `$sDBy520~@P2#`

**Comment by StevenVanDyk** [comment]
Ok
I get the Conversion log
***@***.***D73C3D.07BC94F0]The Character name updates on the actor list
But the Sheet does not
And if I close the sheet I cannot reopen it ..
***@***.***D73C3D.07BC94F0]
***@***.***D73C3D.07BC94F0]

I have all other modules off and I’m using the 0.7.9 release.

Any thoughts on where I could look?

**Comment by StevenVanDyk** [comment]
😐

I have been checking for updates on the modules
And the base version
I missed checking for updates o the pf2nd
:/

I just went back to look through it and Did the update and it now imported.

I’ll add that on my update list 😐


Thanks for the help its much appreceated

**Comment by StevenVanDyk** [comment]
One odd item

When importing his ac is really impressive
***@***.***D73C4A.50D67F40]

In hlo is
***@***.***D73C4A.50D67F40]

When I goto the inventory for him  and unequit his leather armor it drops to 13
Equipping the armor again  brings it back to 1032

It is imported over (I tried with a test character so empty base)
For now I just added it back in with in foundry.

Thanks again

**Comment by zarmstrong** [comment]
The pictures don't come through from email responses to this. Can you  add them directly in GitHub?

**Comment by StevenVanDyk** [comment]
Will do

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by StevenVanDyk** [comment]
One odd item
![hlo ac](https://user-images.githubusercontent.com/63728652/116484322-d6d6fe80-a856-11eb-8341-f82225db4368.png)
![ac](https://user-images.githubusercontent.com/63728652/116484324-d76f9500-a856-11eb-963a-83d0aa2335ec.png)

When importing his ac is really impressive
 

In hlo is
 

When I goto the inventory for him  and unequit his leather armor it drops to 13
Equipping the armor again  brings it back to 1032

It is imported over (I tried with a test character so empty base)
For now I just added it back in with in foundry.

Thanks again

**Comment by zarmstrong** [comment]
Pushed out some changes that should fix this. You will need to update the module. Let me know how it looks after you update.

**Comment by StevenVanDyk** [comment]
Just got a Chance to test it out
And works perfect

Thanks  😊

**Comment by zarmstrong** [comment]
Great! Closing this
