### ISSUE TITLE
Module can be enabled in other systems

### ISSUE THREAD

**Issue by wildj79** [zarmstrong/hlo-importer#9]
Currently, it is possible to enable this module in a system other than Pathfinder, 2nd edition. Adding a `dependencies` property to your `module.json` file would prevent this.

```javascript
{
    // ...Other stuff
    "dependencies": [
        { "name": "pf2e", "type": "system" }
    ],
    // ...Other stuff
}
```

**Comment by zarmstrong** [comment]
Thanks for pointing that out!  I updated the module to prevent this.
